[package]
name  = "wasm"
version = "0.1.0"
authors = ["David Himmelstrup <lemmih@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
base64       = "*"
rand         = "0.8"
getrandom    = { version="0.2.2", features=["js"] }
num-traits   = "0.1"
num-rational = "0.4"
num-bigint   = "*"
rgeometry    = { path="../../" }
rgeometry-wasm = { git="https://github.com/rgeometry/rgeometry-wasm", branch="main" }
#rgeometry-wasm = { path = "../../../rgeometry-wasm" }
wasm-bindgen = "0.2.63"
gloo-events = "*"
parking_lot = "*"
once_cell = "*"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version="0.1.6", optional=true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version="0.4.5", optional=true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
js-sys          = "0.3.51"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

#[package.metadata.wasm-pack.profile.release]
#wasm-opt = false

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'Path2d',
  'HtmlCanvasElement',
  'HtmlInputElement',
  'InputEvent',
  'TouchEvent',
  'Window',
]

[patch."https://github.com/rgeometry/rgeometry"]
rgeometry = { path="../.." }
